# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"\x1a\n\nArrayInt64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x03\"\x1b\n\x0b\x41rrayUint64\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x04\"\x1b\n\x0b\x41rrayDouble\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\"\x1b\n\x0b\x41rrayString\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\"*\n\nArrayValue\x12\x1c\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0e.context_value\"l\n\tMapString\x12\"\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x14.MapString.DataEntry\x1a;\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.context_value:\x02\x38\x01\"\x87\x04\n\rcontext_value\x12\x0e\n\x04\x62ool\x18\x01 \x01(\x08H\x00\x12\x0f\n\x05\x66loat\x18\x02 \x01(\x02H\x00\x12\x10\n\x06\x64ouble\x18\x03 \x01(\x01H\x00\x12\x10\n\x06uint32\x18\x04 \x01(\rH\x00\x12\x10\n\x06uint64\x18\x05 \x01(\x04H\x00\x12\x0f\n\x05int32\x18\x06 \x01(\x05H\x00\x12\x0f\n\x05int64\x18\x07 \x01(\x03H\x00\x12\x10\n\x06sint32\x18\x08 \x01(\x11H\x00\x12\x10\n\x06sint64\x18\t \x01(\x12H\x00\x12\x11\n\x07\x66ixed32\x18\n \x01(\x07H\x00\x12\x11\n\x07\x66ixed64\x18\x0b \x01(\x06H\x00\x12\x12\n\x08sfixed32\x18\x0c \x01(\x0fH\x00\x12\x12\n\x08sfixed64\x18\r \x01(\x10H\x00\x12\x10\n\x06string\x18\x0e \x01(\tH\x00\x12\x0f\n\x05\x62ytes\x18\x0f \x01(\x0cH\x00\x12\"\n\x0b\x61rray_int64\x18\x10 \x01(\x0b\x32\x0b.ArrayInt64H\x00\x12$\n\x0c\x61rray_uint64\x18\x11 \x01(\x0b\x32\x0c.ArrayUint64H\x00\x12$\n\x0c\x61rray_double\x18\x12 \x01(\x0b\x32\x0c.ArrayDoubleH\x00\x12$\n\x0c\x61rray_string\x18\x13 \x01(\x0b\x32\x0c.ArrayStringH\x00\x12\"\n\x0b\x61rray_value\x18\x14 \x01(\x0b\x32\x0b.ArrayValueH\x00\x12 \n\nmap_string\x18\x15 \x01(\x0b\x32\n.MapStringH\x00\x42\x0c\n\nvalue_type\"\x85\x01\n\x0cMatchRuleReq\x12\x32\n\x0b\x63ontext_map\x18\x01 \x03(\x0b\x32\x1d.MatchRuleReq.ContextMapEntry\x1a\x41\n\x0f\x43ontextMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.context_value:\x02\x38\x01\x62\x06proto3'
)




_ARRAYINT64 = _descriptor.Descriptor(
  name='ArrayInt64',
  full_name='ArrayInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArrayInt64.data', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=40,
)


_ARRAYUINT64 = _descriptor.Descriptor(
  name='ArrayUint64',
  full_name='ArrayUint64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArrayUint64.data', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=69,
)


_ARRAYDOUBLE = _descriptor.Descriptor(
  name='ArrayDouble',
  full_name='ArrayDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArrayDouble.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=98,
)


_ARRAYSTRING = _descriptor.Descriptor(
  name='ArrayString',
  full_name='ArrayString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArrayString.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=127,
)


_ARRAYVALUE = _descriptor.Descriptor(
  name='ArrayValue',
  full_name='ArrayValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArrayValue.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=171,
)


_MAPSTRING_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='MapString.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MapString.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MapString.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=281,
)

_MAPSTRING = _descriptor.Descriptor(
  name='MapString',
  full_name='MapString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='MapString.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAPSTRING_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=281,
)


_CONTEXT_VALUE = _descriptor.Descriptor(
  name='context_value',
  full_name='context_value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bool', full_name='context_value.bool', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float', full_name='context_value.float', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double', full_name='context_value.double', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint32', full_name='context_value.uint32', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint64', full_name='context_value.uint64', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int32', full_name='context_value.int32', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int64', full_name='context_value.int64', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sint32', full_name='context_value.sint32', index=7,
      number=8, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sint64', full_name='context_value.sint64', index=8,
      number=9, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed32', full_name='context_value.fixed32', index=9,
      number=10, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fixed64', full_name='context_value.fixed64', index=10,
      number=11, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sfixed32', full_name='context_value.sfixed32', index=11,
      number=12, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sfixed64', full_name='context_value.sfixed64', index=12,
      number=13, type=16, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string', full_name='context_value.string', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='context_value.bytes', index=14,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_int64', full_name='context_value.array_int64', index=15,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_uint64', full_name='context_value.array_uint64', index=16,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_double', full_name='context_value.array_double', index=17,
      number=18, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_string', full_name='context_value.array_string', index=18,
      number=19, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='array_value', full_name='context_value.array_value', index=19,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_string', full_name='context_value.map_string', index=20,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value_type', full_name='context_value.value_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=284,
  serialized_end=803,
)


_MATCHRULEREQ_CONTEXTMAPENTRY = _descriptor.Descriptor(
  name='ContextMapEntry',
  full_name='MatchRuleReq.ContextMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MatchRuleReq.ContextMapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MatchRuleReq.ContextMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=874,
  serialized_end=939,
)

_MATCHRULEREQ = _descriptor.Descriptor(
  name='MatchRuleReq',
  full_name='MatchRuleReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_map', full_name='MatchRuleReq.context_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MATCHRULEREQ_CONTEXTMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=806,
  serialized_end=939,
)

_ARRAYVALUE.fields_by_name['data'].message_type = _CONTEXT_VALUE
_MAPSTRING_DATAENTRY.fields_by_name['value'].message_type = _CONTEXT_VALUE
_MAPSTRING_DATAENTRY.containing_type = _MAPSTRING
_MAPSTRING.fields_by_name['data'].message_type = _MAPSTRING_DATAENTRY
_CONTEXT_VALUE.fields_by_name['array_int64'].message_type = _ARRAYINT64
_CONTEXT_VALUE.fields_by_name['array_uint64'].message_type = _ARRAYUINT64
_CONTEXT_VALUE.fields_by_name['array_double'].message_type = _ARRAYDOUBLE
_CONTEXT_VALUE.fields_by_name['array_string'].message_type = _ARRAYSTRING
_CONTEXT_VALUE.fields_by_name['array_value'].message_type = _ARRAYVALUE
_CONTEXT_VALUE.fields_by_name['map_string'].message_type = _MAPSTRING
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['bool'])
_CONTEXT_VALUE.fields_by_name['bool'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['float'])
_CONTEXT_VALUE.fields_by_name['float'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['double'])
_CONTEXT_VALUE.fields_by_name['double'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['uint32'])
_CONTEXT_VALUE.fields_by_name['uint32'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['uint64'])
_CONTEXT_VALUE.fields_by_name['uint64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['int32'])
_CONTEXT_VALUE.fields_by_name['int32'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['int64'])
_CONTEXT_VALUE.fields_by_name['int64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['sint32'])
_CONTEXT_VALUE.fields_by_name['sint32'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['sint64'])
_CONTEXT_VALUE.fields_by_name['sint64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['fixed32'])
_CONTEXT_VALUE.fields_by_name['fixed32'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['fixed64'])
_CONTEXT_VALUE.fields_by_name['fixed64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['sfixed32'])
_CONTEXT_VALUE.fields_by_name['sfixed32'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['sfixed64'])
_CONTEXT_VALUE.fields_by_name['sfixed64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['string'])
_CONTEXT_VALUE.fields_by_name['string'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['bytes'])
_CONTEXT_VALUE.fields_by_name['bytes'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['array_int64'])
_CONTEXT_VALUE.fields_by_name['array_int64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['array_uint64'])
_CONTEXT_VALUE.fields_by_name['array_uint64'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['array_double'])
_CONTEXT_VALUE.fields_by_name['array_double'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['array_string'])
_CONTEXT_VALUE.fields_by_name['array_string'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['array_value'])
_CONTEXT_VALUE.fields_by_name['array_value'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_CONTEXT_VALUE.oneofs_by_name['value_type'].fields.append(
  _CONTEXT_VALUE.fields_by_name['map_string'])
_CONTEXT_VALUE.fields_by_name['map_string'].containing_oneof = _CONTEXT_VALUE.oneofs_by_name['value_type']
_MATCHRULEREQ_CONTEXTMAPENTRY.fields_by_name['value'].message_type = _CONTEXT_VALUE
_MATCHRULEREQ_CONTEXTMAPENTRY.containing_type = _MATCHRULEREQ
_MATCHRULEREQ.fields_by_name['context_map'].message_type = _MATCHRULEREQ_CONTEXTMAPENTRY
DESCRIPTOR.message_types_by_name['ArrayInt64'] = _ARRAYINT64
DESCRIPTOR.message_types_by_name['ArrayUint64'] = _ARRAYUINT64
DESCRIPTOR.message_types_by_name['ArrayDouble'] = _ARRAYDOUBLE
DESCRIPTOR.message_types_by_name['ArrayString'] = _ARRAYSTRING
DESCRIPTOR.message_types_by_name['ArrayValue'] = _ARRAYVALUE
DESCRIPTOR.message_types_by_name['MapString'] = _MAPSTRING
DESCRIPTOR.message_types_by_name['context_value'] = _CONTEXT_VALUE
DESCRIPTOR.message_types_by_name['MatchRuleReq'] = _MATCHRULEREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArrayInt64 = _reflection.GeneratedProtocolMessageType('ArrayInt64', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYINT64,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ArrayInt64)
  })
_sym_db.RegisterMessage(ArrayInt64)

ArrayUint64 = _reflection.GeneratedProtocolMessageType('ArrayUint64', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYUINT64,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ArrayUint64)
  })
_sym_db.RegisterMessage(ArrayUint64)

ArrayDouble = _reflection.GeneratedProtocolMessageType('ArrayDouble', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYDOUBLE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ArrayDouble)
  })
_sym_db.RegisterMessage(ArrayDouble)

ArrayString = _reflection.GeneratedProtocolMessageType('ArrayString', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYSTRING,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ArrayString)
  })
_sym_db.RegisterMessage(ArrayString)

ArrayValue = _reflection.GeneratedProtocolMessageType('ArrayValue', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYVALUE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:ArrayValue)
  })
_sym_db.RegisterMessage(ArrayValue)

MapString = _reflection.GeneratedProtocolMessageType('MapString', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _MAPSTRING_DATAENTRY,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:MapString.DataEntry)
    })
  ,
  'DESCRIPTOR' : _MAPSTRING,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:MapString)
  })
_sym_db.RegisterMessage(MapString)
_sym_db.RegisterMessage(MapString.DataEntry)

context_value = _reflection.GeneratedProtocolMessageType('context_value', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT_VALUE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:context_value)
  })
_sym_db.RegisterMessage(context_value)

MatchRuleReq = _reflection.GeneratedProtocolMessageType('MatchRuleReq', (_message.Message,), {

  'ContextMapEntry' : _reflection.GeneratedProtocolMessageType('ContextMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _MATCHRULEREQ_CONTEXTMAPENTRY,
    '__module__' : 'data_pb2'
    # @@protoc_insertion_point(class_scope:MatchRuleReq.ContextMapEntry)
    })
  ,
  'DESCRIPTOR' : _MATCHRULEREQ,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:MatchRuleReq)
  })
_sym_db.RegisterMessage(MatchRuleReq)
_sym_db.RegisterMessage(MatchRuleReq.ContextMapEntry)


_MAPSTRING_DATAENTRY._options = None
_MATCHRULEREQ_CONTEXTMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
